"""MCP tools for the OWS knowledge vault — local Obsidian vault, no network.

The knowledge lives in an **Obsidian-standard vault** at `docs/help/vault/`:

    docs/help/vault/
        Home.md                  MOC top node (git-tracked)
        00 Findings/*.md         human-curated, evolving findings (git-tracked)
        Reference/<nav tree>/*.md auto-generated OWS help corpus (gitignored)
    docs/help/index/<lang>/
        nav_index.json           flat [{id, parent_id, name, local, depth, path}]
        topics.jsonl             [{id, name, local, title, text}] fast-search sidecar

Two layers, two lifecycles:

- **Reference/** is the ~3.6k-page OWS help corpus, regenerated by
  `scripts/import_help_corpus.py` (copied verbatim from the scraped vault so
  it stays Obsidian-navigable). It is gitignored — regenerable, not shipped.
- **00 Findings/** + **Home.md** are hand-curated and git-tracked. Anyone can
  add a findings note; the importer never touches them.

These tools make **findings the first thing an agent reads**: `get_help_home`
returns the MOC, and `search_help` ranks `00 Findings/` hits above the raw
Reference corpus — so a curated summary short-circuits a full-corpus search.

This file makes NO live network calls. If the cache is missing the tools return
a structured `error.no_cache` telling the caller how to populate it.
"""

from __future__ import annotations

import json
import os
import re
from html.parser import HTMLParser
from pathlib import Path
from typing import Any

from ows_gde_mcp.config import settings as _settings

# Curated, git-tracked parts of the vault.
_FINDINGS_DIR = "00 Findings"
_HOME_FILE = "Home.md"

# Default language. The Reference corpus is currently en_US only.
_DEFAULT_LANG = "en_US"


def _vault_root() -> Path:
    """Resolve the knowledge-vault directory (writable, per-project by default).

    Resolution order:
      1. ``OWS_VAULT_DIR`` — from `.env` (Settings) or the environment.
      2. ``<cwd>/ows-vault`` — per-project default.

    Resolved per call so the location can change at runtime and so the env var
    (set by the plugin, the user's shell, or a test) always wins. Findings the
    end user adds live here; the importer writes ``Reference/`` and the search
    index here too.
    """
    # Live env wins (plugin / shell / test override); then .env via Settings.
    configured = os.environ.get("OWS_VAULT_DIR") or _settings.OWS_VAULT_DIR
    if configured:
        return Path(configured).expanduser()
    return Path.cwd() / "ows-vault"


def _index_dir(lang: str = _DEFAULT_LANG) -> Path:
    # Hidden, gitignored sidecar search index inside the vault dir.
    return _vault_root() / ".index" / lang


def _findings_dir() -> Path:
    return _vault_root() / _FINDINGS_DIR


def _no_cache_error(lang: str) -> dict[str, Any]:
    return {
        "error": {
            "code": "no_cache",
            "message": (
                f"Help index for {lang!r} is empty at {_index_dir(lang)} and no "
                f"findings exist at {_findings_dir()}. Populate the Reference "
                "corpus with `uv run python scripts/import_help_corpus.py "
                "--vault ~/codes/huaweed/knowledge-helper/vault`, and/or add a "
                f"note under '{_FINDINGS_DIR}/'."
            ),
        }
    }


def _load_index(lang: str) -> list[dict] | None:
    path = _index_dir(lang) / "nav_index.json"
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None


# ---------------- HTML extraction (legacy fetch_help_docs.py output) ----------


class _TopicTextExtractor(HTMLParser):
    """Pull title + plain text from a legacy OWS help topic HTML page.

    Only used for `.html` topics produced by `scripts/fetch_help_docs.py`. The
    vault Reference corpus is Markdown, which is served as-is.
    """

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self._buf: list[str] = []
        self._stack: list[str] = []
        self._title: str | None = None
        self._in_title = False
        self._suppress = 0  # >0 inside <script>/<style>
        self._block_tags = {
            "p", "li", "h1", "h2", "h3", "h4", "h5", "h6",
            "br", "tr", "td", "th", "div", "ul", "ol",
        }
        self._parent_topic: tuple[str, str] | None = None
        self._in_parentlink = False
        self._link_target: str | None = None

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        self._stack.append(tag)
        attrs_d = dict(attrs)
        if tag == "script" or tag == "style":
            self._suppress += 1
            return
        if tag == "h1" and "topictitle1" in (attrs_d.get("class") or ""):
            self._in_title = True
        if tag == "div" and "parentlink" in (attrs_d.get("class") or ""):
            self._in_parentlink = True
        if tag == "a" and self._in_parentlink:
            self._link_target = attrs_d.get("href")

    def handle_endtag(self, tag: str) -> None:
        if (tag == "script" or tag == "style") and self._suppress > 0:
            self._suppress -= 1
        if tag == "h1":
            self._in_title = False
        if tag == "div" and self._in_parentlink:
            self._in_parentlink = False
        if tag in self._block_tags:
            self._buf.append("\n")
        if self._stack and self._stack[-1] == tag:
            self._stack.pop()

    def handle_data(self, data: str) -> None:
        if self._suppress:
            return
        if self._in_title:
            self._title = (self._title or "") + data
            return
        if self._in_parentlink and self._link_target and data.strip():
            self._parent_topic = (data.strip(), self._link_target)
            self._link_target = None
        self._buf.append(data)

    @property
    def title(self) -> str | None:
        return self._title.strip() if self._title else None

    @property
    def text(self) -> str:
        joined = "".join(self._buf)
        return re.sub(r"\n{3,}", "\n\n", joined).strip()

    @property
    def parent_topic(self) -> dict[str, str] | None:
        if not self._parent_topic:
            return None
        name, href = self._parent_topic
        return {"name": name, "local": href}


def _extract_topic_body(html: str) -> tuple[str | None, str, dict | None]:
    p = _TopicTextExtractor()
    p.feed(html)
    return p.title, p.text, p.parent_topic


def _md_title(raw: str) -> str | None:
    """First ATX heading (`# ...`) of a markdown body, else None."""
    for line in raw.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return None


# ---------------- Public MCP tools ----------------


def get_help_home(*, lang: str = _DEFAULT_LANG) -> dict[str, Any]:
    """Return the knowledge-vault home page (the MOC top node).

    Reads `docs/help/vault/Home.md` — a hand-curated Map of Content that links
    the curated findings and the Reference corpus roots. **Read this first**:
    it's the cheapest way to orient before searching the full corpus, and it's
    where participants point you at the high-signal findings.

    Args:
        lang: reserved for future multi-language homes. Currently the vault is
            single-home; `lang` is accepted for API symmetry.

    Returns:
        `{"title", "text", "local", "findings": [{name, local}]}` or
        `{"error": {"code": "no_home", ...}}` if the vault hasn't been set up.
    """
    home = _vault_root() / _HOME_FILE
    if not home.exists():
        return {
            "error": {
                "code": "no_home",
                "message": (
                    f"No vault home at {home}. Create docs/help/vault/Home.md "
                    "(a Map of Content) and add findings under "
                    f"'{_FINDINGS_DIR}/'."
                ),
            }
        }
    raw = home.read_text(encoding="utf-8")
    findings = (
        [
            {"name": p.stem, "local": f"{_FINDINGS_DIR}/{p.name}"}
            for p in sorted(_findings_dir().glob("*.md"))
        ]
        if _findings_dir().is_dir()
        else []
    )
    return {
        "title": _md_title(raw) or "Home",
        "text": raw,
        "local": _HOME_FILE,
        "findings": findings,
        "lang": lang,
    }


def list_help_topics(
    *,
    query: str = "",
    parent_id: int | None = None,
    depth_max: int | None = None,
    lang: str = _DEFAULT_LANG,
    limit: int = 50,
) -> dict[str, Any]:
    """List topics from the Reference corpus nav index.

    Reads `docs/help/index/<lang>/nav_index.json` — built by
    `scripts/import_help_corpus.py`. No live network calls.

    Args:
        query: substring filter on topic name (case-insensitive). Empty = all.
        parent_id: keep only direct children of this parent. None = all.
        depth_max: keep only topics at this nav depth or shallower.
        lang: language directory under `docs/help/index/`. Default `en_US`.
        limit: cap the number of rows returned (default 50).

    Returns:
        `{"total", "lang", "topics": [{id, parent_id, name, local, depth,
          is_folder}]}` or `{"error": {"code": "no_cache", ...}}`.
    """
    index = _load_index(lang)
    if index is None:
        return _no_cache_error(lang)

    q = query.lower().strip()
    matches = []
    for row in index:
        if q and q not in (row.get("name") or "").lower():
            continue
        if parent_id is not None and row.get("parent_id") != parent_id:
            continue
        if depth_max is not None and row.get("depth", 0) > depth_max:
            continue
        matches.append(
            {
                "id": row.get("id"),
                "parent_id": row.get("parent_id"),
                "name": row.get("name"),
                "local": row.get("local"),
                "depth": row.get("depth", 0),
                "is_folder": row.get("is_folder", False),
            }
        )
    return {
        "total": len(matches),
        "lang": lang,
        "topics": matches[:limit],
    }


def get_help_topic(
    topic: int | str,
    *,
    lang: str = _DEFAULT_LANG,
    include_raw: bool = False,
) -> dict[str, Any]:
    """Fetch one topic or finding from the local vault.

    Args:
        topic: an integer Reference `id`, a Reference `local` path
            (e.g. `"Reference/Low-Code Orchestration/.../X.md"`), OR any vault
            markdown path including a finding
            (e.g. `"00 Findings/OWS Platform Findings.md"`). Finding paths are
            served even though they aren't in the Reference nav index.
        lang: index language for id/local lookup. Default `en_US`.
        include_raw: if True, also return the raw file body under `raw`.

    Returns:
        `{"id", "name", "local", "title", "text", "parent", "breadcrumbs",
          "source"}` where `source` is "reference" or "finding", or
        `{"error": {...}}`.
    """
    index = _load_index(lang) or []
    by_id = {r["id"]: r for r in index if r.get("id") is not None}
    by_local = {r["local"]: r for r in index if r.get("local")}

    row: dict | None = None
    if isinstance(topic, int) or (isinstance(topic, str) and topic.isdigit()):
        row = by_id.get(int(topic))
    elif isinstance(topic, str):
        row = by_local.get(topic)

    # Resolve the on-disk path. Reference rows live under the vault; a bare
    # markdown path (e.g. a finding) is served directly if it exists in the
    # vault, even when absent from the nav index.
    if row is not None:
        rel = row["local"]
    elif isinstance(topic, str) and topic.endswith(".md"):
        rel = topic
    else:
        if not index:
            return _no_cache_error(lang)
        return {"error": {"code": "not_found", "message": f"Topic {topic!r} not in nav."}}

    source = "finding" if str(rel).startswith(f"{_FINDINGS_DIR}/") else "reference"

    vault_root = _vault_root().resolve()
    file_path = (vault_root / rel).resolve()
    # Confinement: never read outside the vault, whatever `rel` claims.
    if file_path != vault_root and vault_root not in file_path.parents:
        return {"error": {"code": "invalid_path", "message": f"Path escapes the vault: {rel!r}"}}
    if not file_path.exists():
        return {
            "error": {
                "code": "missing_file",
                "message": (
                    f"Topic {topic!r} resolves to {file_path}, which is missing. "
                    "Re-run the importer or check the path."
                ),
            }
        }

    raw = file_path.read_text(encoding="utf-8")
    if str(rel).endswith(".md"):
        title, text, parent = _md_title(raw), raw, None
    else:
        title, text, parent = _extract_topic_body(raw)

    breadcrumbs: list[dict[str, Any]] = []
    if row is not None:
        for nid in row.get("path") or []:
            crumb = by_id.get(nid)
            if crumb:
                breadcrumbs.append({"id": nid, "name": crumb.get("name")})

    out: dict[str, Any] = {
        "id": row.get("id") if row else None,
        "name": (row.get("name") if row else None) or title,
        "local": str(rel),
        "title": title,
        "text": text,
        "parent": parent,
        "breadcrumbs": breadcrumbs,
        "source": source,
        "lang": lang,
    }
    if include_raw:
        out["raw"] = raw
    return out


def search_help(
    query: str,
    *,
    lang: str = _DEFAULT_LANG,
    limit: int = 20,
    snippet_chars: int = 240,
) -> dict[str, Any]:
    """Full-text search the vault, **findings first**.

    Curated `00 Findings/` notes are searched live (always fresh — no reindex
    needed when one is added) and ranked ABOVE the Reference corpus, which is
    served from the `topics.jsonl` sidecar index. A finding hit lets an agent
    short-circuit a full-corpus dive.

    Args:
        query: required search string (>=2 chars).
        lang: index language for the Reference corpus.
        limit: cap the total hit list (findings + reference, findings first).
        snippet_chars: characters of context around each match.

    Returns:
        `{"query", "total", "findings_count", "hits": [{id, name, local, title,
          snippet, source}], "lang"}` where `source` is "finding" or
        "reference"; or `{"error": {...}}` on empty query / total cache miss.
    """
    if not query or len(query.strip()) < 2:
        return {
            "error": {
                "code": "query_too_short",
                "message": "Provide a query of at least 2 characters.",
            }
        }

    finding_hits = _search_findings(query, limit, snippet_chars)

    index_path = _index_dir(lang) / "topics.jsonl"
    ref_hits: list[dict[str, Any]] = []
    if index_path.exists():
        ref_hits = _search_jsonl(query, index_path, limit, snippet_chars)
    elif (
        not finding_hits
        and _load_index(lang) is None
        and not _findings_dir().is_dir()
    ):
        # Neither the reference index nor any findings exist — a genuine cache
        # miss, as opposed to a query that simply matched nothing.
        return _no_cache_error(lang)

    hits = (finding_hits + ref_hits)[:limit]
    return {
        "query": query,
        "total": len(hits),
        "findings_count": len(finding_hits),
        "hits": hits,
        "lang": lang,
    }


def _make_snippet(haystack: str, idx: int, snippet_chars: int) -> str:
    start = max(0, idx - snippet_chars // 2)
    end = min(len(haystack), idx + snippet_chars // 2)
    snippet = haystack[start:end]
    if start > 0:
        snippet = "..." + snippet
    if end < len(haystack):
        snippet = snippet + "..."
    return re.sub(r"\s+", " ", snippet).strip()


def _search_findings(query: str, limit: int, snippet_chars: int) -> list[dict[str, Any]]:
    """Scan the curated `00 Findings/` notes live. Returns ranked hits."""
    fdir = _findings_dir()
    if not fdir.is_dir():
        return []
    q = query.lower().strip()
    hits: list[dict[str, Any]] = []
    for path in sorted(fdir.glob("*.md")):
        try:
            raw = path.read_text(encoding="utf-8")
        except OSError:
            continue
        title = _md_title(raw) or path.stem
        haystack = f"{title}\n{raw}"
        idx = haystack.lower().find(q)
        if idx < 0:
            continue
        hits.append(
            {
                "id": None,
                "name": title,
                "local": f"{_FINDINGS_DIR}/{path.name}",
                "title": title,
                "snippet": _make_snippet(haystack, idx, snippet_chars),
                "source": "finding",
            }
        )
        if len(hits) >= limit:
            break
    return hits


def _search_jsonl(
    query: str, index_path: Path, limit: int, snippet_chars: int
) -> list[dict[str, Any]]:
    q = query.lower().strip()
    hits: list[dict[str, Any]] = []
    with index_path.open(encoding="utf-8") as f:
        for line in f:
            try:
                entry = json.loads(line)
            except ValueError:
                continue
            haystack = f"{entry.get('title') or ''}\n{entry.get('text') or ''}"
            idx = haystack.lower().find(q)
            if idx < 0:
                continue
            hits.append(
                {
                    "id": entry.get("id"),
                    "name": entry.get("name"),
                    "local": entry.get("local"),
                    "title": entry.get("title"),
                    "snippet": _make_snippet(haystack, idx, snippet_chars),
                    "source": "reference",
                }
            )
            if len(hits) >= limit:
                break
    return hits


def _slugify(title: str) -> str:
    """Filesystem-safe finding filename from a title (no path separators)."""
    slug = re.sub(r"[^A-Za-z0-9 _-]", "", title).strip()
    slug = re.sub(r"\s+", " ", slug)
    return slug or "untitled"


def add_help_finding(
    title: str,
    body: str,
    *,
    tags: list[str] | None = None,
    overwrite: bool = False,
) -> dict[str, Any]:
    """Create or update a curated finding in the vault's `00 Findings/` folder.

    This is how the knowledge vault evolves: when you confirm a reusable,
    non-obvious platform fact, capture it as a short finding so future sessions
    (and other participants) read it first via `get_help_home` / `search_help`.

    Writes `<vault>/00 Findings/<title>.md` with optional YAML front-matter
    (tags) and a `# <title>` heading. The write is confined to the findings
    folder. Before adding, prefer checking `search_help(title)` to update an
    existing finding instead of creating a near-duplicate.

    Args:
        title: short, specific finding title (also the filename). Required.
        body: the finding content (markdown). Keep it terse and
            production-confirmed. Required.
        tags: optional list of tags for the front-matter.
        overwrite: if a finding with this title exists, replace it. Default
            False returns an `exists` error so you don't clobber by accident.

    Returns:
        `{"ok": True, "local", "path", "title"}` on success, or
        `{"error": {...}}` (codes: `bad_input`, `exists`).
    """
    if not title or not title.strip():
        return {"error": {"code": "bad_input", "message": "title is required."}}
    if not body or not body.strip():
        return {"error": {"code": "bad_input", "message": "body is required."}}

    fdir = _findings_dir()
    fdir.mkdir(parents=True, exist_ok=True)
    slug = _slugify(title)
    path = (fdir / f"{slug}.md").resolve()
    if fdir.resolve() not in path.parents:
        return {"error": {"code": "bad_input", "message": f"Invalid title {title!r}."}}
    if path.exists() and not overwrite:
        return {
            "error": {
                "code": "exists",
                "message": (
                    f"A finding '{slug}.md' already exists. Re-issue with "
                    "overwrite=True to replace it, or choose a different title."
                ),
                "local": f"{_FINDINGS_DIR}/{path.name}",
            }
        }

    tag_list = tags or []
    front = "---\ntags: [" + ", ".join(tag_list) + "]\n---\n" if tag_list else ""
    content = f"{front}# {title.strip()}\n\n{body.strip()}\n"
    path.write_text(content, encoding="utf-8")
    return {
        "ok": True,
        "local": f"{_FINDINGS_DIR}/{path.name}",
        "path": str(path),
        "title": title.strip(),
    }


__all__ = [
    "add_help_finding",
    "get_help_home",
    "get_help_topic",
    "list_help_topics",
    "search_help",
]
